### ISSUE TITLE
missing api key

### ISSUE THREAD

**Issue by moonlags** [Runware/sdk-go#3]
I am always getting missing api key with the ws request timeout follow up. 
```go
	runware, err := runware.NewSDK(runware.SDKConfig{
		APIKey:    os.Getenv("RUNWARE_KEY"),
		KeepAlive: true,
	})
	if err != nil {
		slog.Error("Can not create runware sdk", "err", err)
		os.Exit(1)
```

This program is printing an error despite the fact that runware api key is provided in the .env file and loaded during program startup
```
[readLoop]: {
    "errors": [
        {
            "code": "missingApiKey",
            "message": "Missing API Key. Get one at https://my.runware.ai/signup",
            "parameter": "apiKey",
            "type": "string",
            "taskType": "authentication"
        }
    ]
}
time=2024-08-20T13:16:03.105+03:00 level=INFO msg="Skipping event errors Currently handling newConnectionSessionUUID"
time=2024-08-20T13:16:33.021+03:00 level=ERROR msg="Can not create runware sdk" err="cannot connect to ws:[request timeout:[newConnection]]"
```

**Comment by moonlags** [comment]
After fixing the connection issues in the library myself, I am encountering error with code 5
```
"{\n    \"errors\": [\n      
  {\n            \"code\": 5,\n          
  \"error\": \"standardError\",\n        
    \"message\": \"An error has occurred 
please read documentation for additional 
details or contact support at support@run
ware.ai\",\n            \"documentation\"
: \"https:\/\/docs.runware.ai\",\n       
     \"taskUUID\": \"4ae72bed-979c-49b6-b
415-33b4f6759406\"\n        }\n    ]\n}
```

**Comment by moonlags** [comment]
For working alternative see https://github.com/moonlags/runware-go developed by me.

Contributions are welcomed!

**Comment by felixsanz** [comment]
Hi @moonlags! We've added a lot of improvements/changes in the server API recently. The Python/JS SDKs are updated but this one is a bit behind.

We are working on improving it, but if you feel like it, you could contribute with PRs to this repository and we'll be happy to merge them. Hope you can do it!

Thank you for the feedback and taking the time to develop an alternative yourself.
